name: Deploy GitHub Pages

on:
  push:
    branches:
      - main # Change to your default branch if it's not "main"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: List build output
        run: |
          ls -la dist/
          cat dist/index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.ACCESS_TOKEN }} # Use the PAT here
          publish_dir: ./dist
        #uses: JamesIves/github-pages-deploy-action@v4
        #with:
        #branch: gh-pages # The branch to deploy to
        #folder: dist     # The folder to deploy
        #token: ${{ secrets.ACCESS_TOKEN }} # Use your personal access token here
